### ISSUE TITLE
1.16.3 

### ISSUE THREAD

**Issue by The-King12121** [hugoalh/Minecraft.Java.DataPack.EnchantPlus#5]
Just wanted to know if your gonna update the datapack to 1.16.3 or not

**Comment by hugoalh** [comment]
Update to 1.16.3 is in the plan and still processing, but unfortunately the new enchanting method do not work as expected and causing major lag, because the new method needs a lot of calculations (new dynamic recipe based on status and environment).

Moreover, since some of the recipes are inspected from some mods, such as EnderIO, Construct's Armory, etc., but those mods still have not update to 1.16 yet; as I do not want this data pack to be too OP and keep it in balance, this may took more time and probably another delay.

**Comment by The-King12121** [comment]
cant you make it with just vanilla enchants no need of adding enchants from mods

**Comment by The-King12121** [comment]
Kill 256 Biological Entity (Cumulative) What is this ?

**Comment by hugoalh** [comment]
> Kill 256 Biological Entity (Cumulative) What is this ?
> My friend cant enchant sweeping edge

Biological entity includes any mobs and players, but unfortunately it will enchanting fail due to the table is broken since 1.15.
